### ISSUE TITLE
GTalk integration?

### ISSUE THREAD

**Issue by wavded** [NolanChan/iMessageWorkflow#1]
The original post talked about GTalk integration and it doesn't seem to work for me.  I was expecting to message people in my Buddy (and/or Contact) list but I only have phone numbers.

**Comment by NolanChan** [comment]
Hey, thanks for the feedback! 
I'm trying to narrow down the issue: is the contact you are trying to reach through your Gtalk buddy list in your actual OSX  contact list?

**Comment by wavded** [comment]
Correct.  They have a Google Talk entry (some have a Jabber entry which is also hooked up to the Google Talk account) but I only get Phone numbers.  Is it possible to "chat" at someone with this plugin, that was my hope, although iMessage itself can be nice.

**Comment by NolanChan** [comment]
I think I worded my question confusingly; I was asking if the person you are trying to contact with the plugin exists in your contact book on your computer.

The reason I am asking is that I pull all searchable contacts from your OSX Contacts Application. So if it doesn't even show up, then I don't believe it's in your OSX Contacts Application in the first place (which is my problem, not yours).

Unless your problem is that the Alfred Plugin is always defaulting to using the phone number? This is the "correct" behavior, and I'll have to add some substantial code improvements for the user to distinguish between the two (sending iMessage vs. sending Gtalk to the same contact)

**Comment by wavded** [comment]
Yes, they exist as a contact (meaning they are an entry in the Contacts app). One on my contacts had no phone number but they have a GTalk email and apparently I can't find those? (ran `imu`).  It may be a question of purpose too.  For me, I am looking for a plugin that has your workflow (replies/messaging from Alfred) but integrates essentially my Messages buddy list (all whom use GTalk).

**Comment by NolanChan** [comment]
Yeah, actually at the moment I screen out all contacts that don't have phone numbers because of the way that I create iMessages. Now that this application can "theoretically" use iMessage for GTalk, I will have to change this. Thanks for giving me an update; sorry for not getting back to you, I had a bunch of finals for school
